id: AF1943593
title: 'Cultivating the Pure Realm of Manifest Joy: A Guru Yoga of Vajrasattva'
type: translation
pechas:
- I13D5B0A1
- I363AF4AA
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:42:50.964964
  last_modified_at: 2023-01-04 12:42:50.964985
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I13D5B0A1/1627: '8088'
  I363AF4AA/6648: '8088'
